site_name: Linux on Arm
site_url: https://linuxonarm64.github.io
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    - navigation.sections
    - navigation.footer
plugins:
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/linuxonarm64
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/linuxonarm
  generator: false
